#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cheesebaron.RippleEffect.Resource.Animation.zoom = global::Sample.Resource.Animation.zoom;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rvAlpha = global::Sample.Resource.Attribute.rvAlpha;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rvCentered = global::Sample.Resource.Attribute.rvCentered;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rvColor = global::Sample.Resource.Attribute.rvColor;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rvFramerate = global::Sample.Resource.Attribute.rvFramerate;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rvRippleDuration = global::Sample.Resource.Attribute.rvRippleDuration;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rvType = global::Sample.Resource.Attribute.rvType;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rvZoom = global::Sample.Resource.Attribute.rvZoom;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rvZoomDuration = global::Sample.Resource.Attribute.rvZoomDuration;
			global::Cheesebaron.RippleEffect.Resource.Color.@__rippleViewDefaultColor = global::Sample.Resource.Color.@__rippleViewDefaultColor;
			global::Cheesebaron.RippleEffect.Resource.Drawable.shape_rounded = global::Sample.Resource.Drawable.shape_rounded;
			global::Cheesebaron.RippleEffect.Resource.Id.doubleRipple = global::Sample.Resource.Id.doubleRipple;
			global::Cheesebaron.RippleEffect.Resource.Id.simpleRipple = global::Sample.Resource.Id.simpleRipple;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView = global::Sample.Resource.Styleable.RippleView;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rvAlpha = global::Sample.Resource.Styleable.RippleView_rvAlpha;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rvCentered = global::Sample.Resource.Styleable.RippleView_rvCentered;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rvColor = global::Sample.Resource.Styleable.RippleView_rvColor;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rvFramerate = global::Sample.Resource.Styleable.RippleView_rvFramerate;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rvRippleDuration = global::Sample.Resource.Styleable.RippleView_rvRippleDuration;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rvType = global::Sample.Resource.Styleable.RippleView_rvType;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rvZoom = global::Sample.Resource.Styleable.RippleView_rvZoom;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rvZoomDuration = global::Sample.Resource.Styleable.RippleView_rvZoomDuration;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int zoom = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int rvAlpha = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int rvCentered = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int rvColor = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int rvFramerate = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int rvRippleDuration = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int rvType = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int rvZoom = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int rvZoomDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int @__rippleViewDefaultColor = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_horizontal_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int activity_vertical_margin = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_profil_plus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int shape_example = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int shape_rounded = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int action_settings = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int actionbar = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int doubleRipple = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int more = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int more2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int rect = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int simpleRipple = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int action_settings = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int hello_world = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RippleView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public const int RippleView_rvAlpha = 0;
			
			// aapt resource value: 5
			public const int RippleView_rvCentered = 5;
			
			// aapt resource value: 4
			public const int RippleView_rvColor = 4;
			
			// aapt resource value: 1
			public const int RippleView_rvFramerate = 1;
			
			// aapt resource value: 2
			public const int RippleView_rvRippleDuration = 2;
			
			// aapt resource value: 6
			public const int RippleView_rvType = 6;
			
			// aapt resource value: 7
			public const int RippleView_rvZoom = 7;
			
			// aapt resource value: 3
			public const int RippleView_rvZoomDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
