#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cheesebaron.RippleEffect.Resource.Animation.zoom = global::Sample.Resource.Animation.zoom;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_alpha = global::Sample.Resource.Attribute.rv_alpha;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_centered = global::Sample.Resource.Attribute.rv_centered;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_color = global::Sample.Resource.Attribute.rv_color;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_framerate = global::Sample.Resource.Attribute.rv_framerate;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_rippleDuration = global::Sample.Resource.Attribute.rv_rippleDuration;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_ripplePadding = global::Sample.Resource.Attribute.rv_ripplePadding;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_type = global::Sample.Resource.Attribute.rv_type;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_zoom = global::Sample.Resource.Attribute.rv_zoom;
			global::Cheesebaron.RippleEffect.Resource.Attribute.rv_zoomDuration = global::Sample.Resource.Attribute.rv_zoomDuration;
			global::Cheesebaron.RippleEffect.Resource.Color.@__rippleViewDefaultColor = global::Sample.Resource.Color.@__rippleViewDefaultColor;
			global::Cheesebaron.RippleEffect.Resource.Drawable.shape_rounded = global::Sample.Resource.Drawable.shape_rounded;
			global::Cheesebaron.RippleEffect.Resource.Id.doubleRipple = global::Sample.Resource.Id.doubleRipple;
			global::Cheesebaron.RippleEffect.Resource.Id.rectangle = global::Sample.Resource.Id.rectangle;
			global::Cheesebaron.RippleEffect.Resource.Id.simpleRipple = global::Sample.Resource.Id.simpleRipple;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView = global::Sample.Resource.Styleable.RippleView;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_alpha = global::Sample.Resource.Styleable.RippleView_rv_alpha;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_centered = global::Sample.Resource.Styleable.RippleView_rv_centered;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_color = global::Sample.Resource.Styleable.RippleView_rv_color;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_framerate = global::Sample.Resource.Styleable.RippleView_rv_framerate;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_rippleDuration = global::Sample.Resource.Styleable.RippleView_rv_rippleDuration;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_ripplePadding = global::Sample.Resource.Styleable.RippleView_rv_ripplePadding;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_type = global::Sample.Resource.Styleable.RippleView_rv_type;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_zoom = global::Sample.Resource.Styleable.RippleView_rv_zoom;
			global::Cheesebaron.RippleEffect.Resource.Styleable.RippleView_rv_zoomDuration = global::Sample.Resource.Styleable.RippleView_rv_zoomDuration;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int zoom = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int rv_alpha = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int rv_centered = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int rv_color = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int rv_framerate = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int rv_rippleDuration = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int rv_ripplePadding = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int rv_type = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int rv_zoom = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int rv_zoomDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int @__rippleViewDefaultColor = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_horizontal_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int activity_vertical_margin = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_profil_plus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int shape_example = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int shape_rounded = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int action_settings = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int actionbar = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int button_floating_action = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int doubleRipple = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int floating = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int more = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int more2 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int rect = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int rectangle = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int simpleRipple = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int action_settings = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int hello_world = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RippleView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int RippleView_rv_alpha = 0;
			
			// aapt resource value: 5
			public const int RippleView_rv_centered = 5;
			
			// aapt resource value: 4
			public const int RippleView_rv_color = 4;
			
			// aapt resource value: 1
			public const int RippleView_rv_framerate = 1;
			
			// aapt resource value: 2
			public const int RippleView_rv_rippleDuration = 2;
			
			// aapt resource value: 7
			public const int RippleView_rv_ripplePadding = 7;
			
			// aapt resource value: 6
			public const int RippleView_rv_type = 6;
			
			// aapt resource value: 8
			public const int RippleView_rv_zoom = 8;
			
			// aapt resource value: 3
			public const int RippleView_rv_zoomDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
