#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cheesebaron.RippleEffect.Resource", IsApplication=false)]

namespace Cheesebaron.RippleEffect
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f030000
			public static int zoom = 2130903040;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int rv_alpha = 2130771968;
			
			// aapt resource value: 0x7f010006
			public static int rv_centered = 2130771974;
			
			// aapt resource value: 0x7f010005
			public static int rv_color = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int rv_framerate = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int rv_rippleDuration = 2130771970;
			
			// aapt resource value: 0x7f010008
			public static int rv_ripplePadding = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int rv_type = 2130771975;
			
			// aapt resource value: 0x7f010009
			public static int rv_zoom = 2130771977;
			
			// aapt resource value: 0x7f010003
			public static int rv_zoomDuration = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int rv_zoomScale = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int @__rippleViewDefaultColor = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int shape_rounded = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public static int doubleRipple = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int rectangle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int simpleRipple = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RippleView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public static int RippleView_rv_alpha = 0;
			
			// aapt resource value: 6
			public static int RippleView_rv_centered = 6;
			
			// aapt resource value: 5
			public static int RippleView_rv_color = 5;
			
			// aapt resource value: 1
			public static int RippleView_rv_framerate = 1;
			
			// aapt resource value: 2
			public static int RippleView_rv_rippleDuration = 2;
			
			// aapt resource value: 8
			public static int RippleView_rv_ripplePadding = 8;
			
			// aapt resource value: 7
			public static int RippleView_rv_type = 7;
			
			// aapt resource value: 9
			public static int RippleView_rv_zoom = 9;
			
			// aapt resource value: 3
			public static int RippleView_rv_zoomDuration = 3;
			
			// aapt resource value: 4
			public static int RippleView_rv_zoomScale = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
